// 250 horse names for the racing game. Kept short (<= ~14 chars) so they fit
// the 16-column calculator-style LCD. Used by web/horse.html.
var HORSE_NAMES = [
  "Thunderbolt", "Lightning", "Sonic Boom", "Comet", "Meteor",
  "Blaze", "Wildfire", "Firestorm", "Tempest", "Cyclone",
  "Hurricane", "Typhoon", "Avalanche", "Stampede", "Rampage",
  "Juggernaut", "Velocity", "Turbo", "Nitro", "Rocket",
  "Afterburner", "Quicksilver", "Flash", "Dash", "Streak",
  "Bolt", "Royal Flush", "King's Ransom", "Duke", "Baron",
  "Majesty", "Monarch", "Sovereign", "Regent", "Knight",
  "Crown Jewel", "Emperor", "Sultan", "Midnight", "Storm",
  "Thunder", "Eclipse", "Solstice", "Aurora", "Nova",
  "Galaxy", "Nebula", "Stardust", "Moonshadow", "Sunfire",
  "Starlight", "Daybreak", "Twilight", "Pegasus", "Phoenix",
  "Griffin", "Centaur", "Valkyrie", "Odin", "Thor",
  "Apollo", "Hermes", "Zeus", "Atlas", "Titan",
  "Hercules", "Achilles", "Spartan", "Maximus", "Goliath",
  "Lucky Strike", "Jackpot", "Long Shot", "Dark Horse", "Underdog",
  "Wild Card", "Ace High", "Double Down", "All In", "High Roller",
  "Pay Dirt", "Gold Rush", "Money Maker", "Cash Out", "Hay Fever",
  "Mane Event", "Neigh Sayer", "Sir Loin", "Gallop Poll", "Pony Express",
  "Stable Genius", "Saddle Up", "Horsepower", "Shadow", "Ghost",
  "Phantom", "Specter", "Reaper", "Bandit", "Outlaw",
  "Renegade", "Maverick", "Rebel", "Rogue", "Drifter",
  "Nomad", "Wanderer", "Voyager", "Pioneer", "Pathfinder",
  "Trailblazer", "Silver Bullet", "Golden Boy", "Black Beauty", "Copper Penny",
  "Crimson Tide", "Scarlet", "Indigo", "Onyx", "Jet Black",
  "Smoke", "Ember", "Cinder", "Diesel", "Tornado",
  "Earthquake", "Landslide", "Riptide", "Undertow", "Tsunami",
  "Maelstrom", "Vortex", "Whirlwind", "Gale Force", "Northwind",
  "Zephyr", "Sirocco", "Chinook", "Mistral", "Blizzard",
  "Frostbite", "Iceman", "Glacier", "Polar Star", "Borealis",
  "Solar Flare", "Sunburst", "Heat Wave", "Inferno", "Magma",
  "Lava", "Volcano", "Brimstone", "Hellfire", "Rising Sun",
  "Daredevil", "Hotshot", "Big Shot", "Top Gun", "Sharpshooter",
  "Gunslinger", "Desperado", "Vigilante", "Crusader", "Gladiator",
  "Warrior", "Conqueror", "Warlord", "Centurion", "Legionnaire",
  "Samurai", "Ronin", "Shogun", "Ninja", "Assassin",
  "Predator", "Viper", "Cobra", "Rattler", "Sidewinder",
  "Diamondback", "Mustang", "Bronco", "Stallion", "Wild Stallion",
  "Pinto", "Palomino", "Appaloosa", "Clydesdale", "Secretariat",
  "Seabiscuit", "War Admiral", "Man o' War", "Whirlaway", "Citation",
  "Affirmed", "Seattle Slew", "Triple Crown", "Photo Finish", "Home Stretch",
  "Front Runner", "Wire to Wire", "Neck and Neck", "By a Nose", "Win Place",
  "Daily Double", "Trifecta", "Superfecta", "Exacta", "Long Odds",
  "Even Money", "Sure Thing", "Easy Money", "Fast Track", "Final Lap",
  "Last Call", "Closing Time", "Overtime", "Sudden Death", "Game Over",
  "Checkmate", "Endgame", "Wildflower", "Buttercup", "Daisy Mae",
  "Bluebell", "Marigold", "Dandelion", "Clover", "Honeysuckle",
  "Magnolia", "Willow", "Maple", "Cedar", "Aspen",
  "Birch", "Juniper", "Sage", "Cinnamon", "Nutmeg",
  "Pepper", "Mocha", "Cocoa", "Caramel", "Biscuit",
  "Domino", "Checkers", "Patches", "Dusty", "Sky Dancer"
];

if (typeof module !== "undefined" && module.exports) module.exports = HORSE_NAMES;
